---
- hosts: 192.168.1.49
  remote_user: reda
  become: true
  vars:
    app_name: shop_cart
    app_port: 3000
  tasks:
    # Installer Node.js
    - name: Installer Node.js
      apt:
        name: nodejs
        state: present
      become: true

    # Installer NPM
    - name: Installer NPM
      apt:
        name: npm
        state: present
      become: true

    # Cloner le repo de l'application
    - name: Cloner le repo de l'application
      git:
        repo: https://github.com/Redadjzz/shop_cart.git
        dest: /var/www/shop_cart
        clone: yes
      become: true

    # Installer les dépendances NPM
    - name: Installer les dépendances NPM
      command: npm install
      args:
        chdir: /var/www/shop_cart
      become: true

    # Lancer l'application Node.js en tant que service
    - name: Lancer l'application Node.js en tant que service
      systemd:
        name: {{ app_name }}
        enabled: true
        state: started
        user: root
        environment: "PORT=8082"
        command: /usr/bin/node /var/www/shop_cart/app.js
      become: true
